version: 2

updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/tests/apiserver/testserver"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Helsinki"
    groups:
      go-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Helsinki"
    groups:
      npm-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Helsinki"
    groups:
      actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/bench"
      - "/jepsen/control"
      - "/jepsen/node"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Helsinki"
    groups:
      docker-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
