{{- if and (not .Values.s3.useIRSA) (not .Values.s3.existingSecret) .Values.s3.credentials.accessKeyId .Values.s3.credentials.secretAccessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "t4.fullname" . }}-s3
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "t4.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.s3.credentials.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.credentials.secretAccessKey | quote }}
{{- end }}
