{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "t4.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "t4.labels" . | nindent 4 }}
  annotations:
    {{- if and .Values.s3.useIRSA .Values.s3.iamRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.s3.iamRoleArn | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
