# Client-facing ClusterIP service.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "t4.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "t4.labels" . | nindent 4 }}
  {{- if or .Values.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "t4.selectorLabels" . | nindent 4 }}
  ports:
    - name: client
      port: {{ .Values.service.port }}
      targetPort: client
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
