{{- if and .Values.s3server.enabled .Values.s3server.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "t4.s3server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "t4.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.s3server.persistence.storageClass }}
  storageClassName: {{ if eq .Values.s3server.persistence.storageClass "-" }}""{{- else }}{{ .Values.s3server.persistence.storageClass }}{{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.s3server.persistence.size }}
{{- end }}
